// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Bb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestCcServiceClient is the client API for TestCcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestCcServiceClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type testCcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestCcServiceClient(cc grpc.ClientConnInterface) TestCcServiceClient {
	return &testCcServiceClient{cc}
}

func (c *testCcServiceClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/Aa.Bb.TestCcService/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testCcServiceClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/Aa.Bb.TestCcService/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestCcServiceServer is the server API for TestCcService service.
// All implementations must embed UnimplementedTestCcServiceServer
// for forward compatibility
type TestCcServiceServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedTestCcServiceServer()
}

// UnimplementedTestCcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestCcServiceServer struct {
}

func (UnimplementedTestCcServiceServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedTestCcServiceServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedTestCcServiceServer) mustEmbedUnimplementedTestCcServiceServer() {}

// UnsafeTestCcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestCcServiceServer will
// result in compilation errors.
type UnsafeTestCcServiceServer interface {
	mustEmbedUnimplementedTestCcServiceServer()
}

func RegisterTestCcServiceServer(s grpc.ServiceRegistrar, srv TestCcServiceServer) {
	s.RegisterService(&TestCcService_ServiceDesc, srv)
}

func _TestCcService_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestCcServiceServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aa.Bb.TestCcService/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestCcServiceServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestCcService_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestCcServiceServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aa.Bb.TestCcService/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestCcServiceServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestCcService_ServiceDesc is the grpc.ServiceDesc for TestCcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestCcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Aa.Bb.TestCcService",
	HandlerType: (*TestCcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _TestCcService_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _TestCcService_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Cc.proto",
}
